export default {
  searchInformation: {
    searchTime: 0.156628,
    formattedSearchTime: '0.16',
    totalResults: '1230000',
    formattedTotalResults: '8',
  },
  items: [
    {
      type: 'reddit',
      author: 'rasmus1254',
      sub: 'QualityReps',
      link: 'https://www.reddit.com//r/QualityReps/comments/ym2h1k/finally_got_my_balenciaga_ravers_in_hand_and_i_am/',
      data: 'Finally got Balenciaga Ravers hand disappointed amount flaws',
      score: -0.43,
      upvotes: 1,
      comments: 0,
    },
    {
      type: 'reddit',
      author: 'rasmus1254',
      sub: 'QualityReps',
      link: 'https://www.reddit.com//r/QualityReps/comments/ym2h1k/finally_got_my_balenciaga_ravers_in_hand_and_i_am/',
      data: 'Finally got Balenciaga Ravers hand disappointed amount flaws',
      score: -0.43,
      upvotes: 1,
      comments: 0,
    },
    {
      type: 'reddit',
      author: 'rasmus1254',
      sub: 'QualityReps',
      link: 'https://www.reddit.com//r/QualityReps/comments/ym2h1k/finally_got_my_balenciaga_ravers_in_hand_and_i_am/',
      data: 'Finally got Balenciaga Ravers hand disappointed amount flaws',
      score: -0.43,
      upvotes: 1,
      comments: 0,
    },
    {
      type: 'reddit',
      author: 'rasmus1254',
      sub: 'QualityReps',
      link: 'https://www.reddit.com//r/QualityReps/comments/ym2h1k/finally_got_my_balenciaga_ravers_in_hand_and_i_am/',
      data: 'Finally got Balenciaga Ravers hand disappointed amount flaws',
      score: -0.43,
      upvotes: 1,
      comments: 0,
    },
  ],
};
