export default {
  _shards: {
    failed: 0,
    skipped: 0,
    successful: 1,
    total: 1,
  },
  hits: {
    hits: [
      {
        _id: 'qCq-BYcBnGSL8phd0at6',
        _index: 'twitter',
        _score: 3.1180918,
        _source: {
          date: '2022-12-08',
          likes: '0',
          original_tweet:
            'Balenciaga Defeating a satanic cult  Balenciaga Exposed  via YouTube',
          processed_tweet:
            "['balenciaga', 'defeating', 'satanic', 'cult', 'balenciaga', 'exposed', 'via', 'youtube']",
          retweets: '0',
          url: 'https://twitter.com/jbusanjalo/status/1601003337976926208',
          username: 'jbusanjalo',
        },
        _type: '_doc',
      },
      {
        _id: 'Wyq-BYcBnGSL8phd0ax6',
        _index: 'twitter',
        _score: 3.1180918,
        _source: {
          date: '2022-12-21',
          likes: '1',
          original_tweet:
            'i need someone to do a thread on the difference between cristobals balenciaga and kerings balenciaga',
          processed_tweet:
            "['need', 'someone', 'thread', 'difference', 'cristobals', 'balenciaga', 'kerings', 'balenciaga']",
          retweets: '0',
          url: 'https://twitter.com/nicholasneIson/status/1605711731157778434',
          username: 'nicholasneIson',
        },
        _type: '_doc',
      },
      {
        _id: 'JCq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-08',
          likes: '0',
          original_tweet: 'balenciaga dis you',
          processed_tweet: "['balenciaga', 'dis']",
          retweets: '0',
          url: 'https://twitter.com/krlwytt/status/1590130394909011968',
          username: 'krlwytt',
        },
        _type: '_doc',
      },
      {
        _id: 'Kiq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-08',
          likes: '0',
          original_tweet: 'BALENCIAGA QUEEN ',
          processed_tweet: "['balenciaga', 'queen']",
          retweets: '0',
          url: 'https://twitter.com/Betoulldashti/status/1590126781054750720',
          username: 'Betoulldashti',
        },
        _type: '_doc',
      },
      {
        _id: 'diq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-14',
          likes: '23',
          original_tweet: 'Madonna in Balenciaga ',
          processed_tweet: "['madonna', 'balenciaga']",
          retweets: '6',
          url: 'https://twitter.com/NewMadonna1/status/1592302679291998211',
          username: 'NewMadonna1',
        },
        _type: '_doc',
      },
      {
        _id: 'oiq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-17',
          likes: '0',
          original_tweet: ' toes down in my balenciaga',
          processed_tweet: "['toes', 'balenciaga']",
          retweets: '0',
          url: 'https://twitter.com/1qspikes/status/1593382125608177664',
          username: '1qspikes',
        },
        _type: '_doc',
      },
      {
        _id: 'wCq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-20',
          likes: '16',
          original_tweet: 'what the fuck balenciaga ',
          processed_tweet: "['fuck', 'balenciaga']",
          retweets: '8',
          url: 'https://twitter.com/budweiserbreath/status/1594479993194684419',
          username: 'budweiserbreath',
        },
        _type: '_doc',
      },
      {
        _id: '0yq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-21',
          likes: '0',
          original_tweet: ' Balenciaga Fall ',
          processed_tweet: "['balenciaga', 'fall']",
          retweets: '0',
          url: 'https://twitter.com/hellzbellzxo/status/1594841013209763840',
          username: 'hellzbellzxo',
        },
        _type: '_doc',
      },
      {
        _id: '2Cq-BYcBnGSL8phd0ap6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-11-22',
          likes: '1',
          original_tweet: 'Balenciaga is pervd out ',
          processed_tweet: "['balenciaga', 'pervd']",
          retweets: '0',
          url: 'https://twitter.com/RisktakerRich/status/1595205348390060033',
          username: 'RisktakerRich',
        },
        _type: '_doc',
      },
      {
        _id: 'tCq-BYcBnGSL8phd0at6',
        _index: 'twitter',
        _score: 3.0924187,
        _source: {
          date: '2022-12-09',
          likes: '2',
          original_tweet: 'Balenciaga princess',
          processed_tweet: "['balenciaga', 'princess']",
          retweets: '0',
          url: 'https://twitter.com/FuckCeejay_/status/1601365911793205248',
          username: 'FuckCeejay_',
        },
        _type: '_doc',
      },
    ],
    max_score: 3.1180918,
    total: {
      relation: 'eq',
      value: 1446,
    },
  },
  timed_out: false,
  took: 2,
};
